### ISSUE TITLE
Deployment Crashed

### ISSUE THREAD

**Issue by ciiiii** [Aviortheking/codestats-readme#16]
**Describe the bug**
[Deployment](https://codestats-readme.vercel.app/api/history/) Crashed.

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**
<img width="793" alt="image" src="https://user-images.githubusercontent.com/28784251/167602570-9fdb99c5-24ec-4763-8403-2e86bb8cd07f.png">

**Additional context**

**Comment by Aviortheking** [comment]
Thanks for the report
It was fixed with 7be0ac3
