### ISSUE TITLE
404 error during generation of svg in this project's readme

### ISSUE THREAD

**Issue by nick-delirium** [Aviortheking/codestats-readme#20]
**Describe the bug**
Requesting the core path to generate an image returns 404 error from vercel: `https://codestats-readme.vercel.app/api?username=aviortheking`

**Expected behavior**
Should work as usual

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**
![image](https://user-images.githubusercontent.com/23126999/203110554-be6f5aad-d9ae-44d1-aa7f-ec136bf2b37e.png)

**Additional context**
Looks like vercel deployment simply died out, since my deployment works fine and codestats haven't changed their api response to break anything

**Comment by Aviortheking** [comment]
Hey sorry for the time to answer!

I had some errors with Vercel and since then I moved from them to another one!

Server is ready for new requests and you can use it on the new URL :D
